name: Deploy to Lambda

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: |
        cd chatbox
        npm install
    
    - name: create environment variable files
      run: |
          echo "LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" >> ./chatbox/.env
          echo "LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }}" >> ./chatbox/.env
    - name: Cache Serverless Framework
      uses: actions/cache@v2
      with:
        path: ~/.npm-global/lib/node_modules/serverless
        key: ${{ runner.os }}-serverless-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-serverless-
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy with Serverless
      run: |
        npm install -g serverless
        cd chatbox        
        serverless deploy
